version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=sportevent'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password'
    ports:
      - '3321:3306'
    command: --default-authentication-plugin=mysql_native_password

