
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=sportevent'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password'
    ports:
      - '3321:3306'
    command: --default-authentication-plugin=mysql_native_password

  web:
    image: 'tomcat:latest'
    ports:
      - '8082:8080'
    volumes:
      - './target/sportEvent-0.0.1-SNAPSHOT.jar:/usr/local/tomcat/webapps/sportEvent-0.0.1-SNAPSHOT.jar'
    depends_on:
      - mysql
